# 1. Load `employee_data.csv` into a DataFrame named 
## Display the first 5 rows and check column data types

In [21]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('employee_data.csv')

In [3]:
df.head(5)

,EmployeeID,Age,Department,JobRole,Attrition,MonthlyIncome,YearsAtCompany,JobSatisfaction,PerformanceRating,PercentSalaryHike,DistanceFromHome,MaritalStatus
0,1001,50,Research & Development,Data Scientist,No,8415,19,1,4,16,20,Married
1,1002,36,Research & Development,Data Scientist,No,6391,19,3,4,21,21,Married
2,1003,29,Sales,Data Scientist,No,14157,17,1,4,22,18,Married
3,1004,42,Sales,Sales Exec,No,14835,13,3,4,18,24,Married
4,1005,40,Sales,Software Engineer,No,8951,16,4,3,22,27,Single

In [4]:
df.dtypes

EmployeeID            int64
Age                   int64
Department           object
JobRole              object
Attrition            object
MonthlyIncome         int64
YearsAtCompany        int64
JobSatisfaction       int64
PerformanceRating     int64
PercentSalaryHike     int64
DistanceFromHome      int64
MaritalStatus        object
dtype: object

# 2. Create a DataFrame `df_rd` containing only employees from the
## 'Research & Development' department.

In [5]:
df_rd = df[df['Department'] == 'Research & Development']

In [6]:
df_rd.head()

,EmployeeID,Age,Department,JobRole,Attrition,MonthlyIncome,YearsAtCompany,JobSatisfaction,PerformanceRating,PercentSalaryHike,DistanceFromHome,MaritalStatus
0,1001,50,Research & Development,Data Scientist,No,8415,19,1,4,16,20,Married
1,1002,36,Research & Development,Data Scientist,No,6391,19,3,4,21,21,Married
5,1006,44,Research & Development,HR Manager,Yes,8468,8,4,3,12,11,Single
6,1007,32,Research & Development,Data Scientist,No,11007,19,2,3,19,2,Married
8,1009,45,Research & Development,Data Scientist,No,12444,1,3,3,16,18,Married

# 3. Find the employee with the highest MonthlyIncome 
## Display theirJobRole and MonthlyIncome

In [9]:
result = df.loc[df['MonthlyIncome'].idxmax(), ['JobRole', 'MonthlyIncome']]
result

JobRole          HR Manager
MonthlyIncome         14954
Name: 28, dtype: object

# 4. Check if there are any missing values (`NaN`) in the dataset.

In [10]:
df.isnull().sum()

EmployeeID           0
Age                  0
Department           0
JobRole              0
Attrition            0
MonthlyIncome        0
YearsAtCompany       0
JobSatisfaction      0
PerformanceRating    0
PercentSalaryHike    0
DistanceFromHome     0
MaritalStatus        0
dtype: int64

# 5. Calculate the average Age for each `JobRole

In [11]:
avg = df.groupby('JobRole')['Age'].mean()
avg

JobRole
Data Scientist       38.771429
HR Manager           39.926829
Lab Technician       38.673469
Sales Exec           44.000000
Software Engineer    40.395349
Name: Age, dtype: float64

# 6. How many employees have left the company? 
## (Count values in the Attrition column)

In [13]:
emp = (df['Attrition'] == 'Yes').sum()
emp

np.int64(33)

# 7. Filter for employees with `PercentSalaryHike > 15 **AND** `PerformanceRating == 4.

In [17]:
filter_emp = ((df['PercentSalaryHike'] > 15) & (df['PerformanceRating'] == 4))
filter_emp

0       True
1       True
2       True
3       True
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

# 8. Create a pivot table showing the **average** `MonthlyIncome
## for each `Department (rows) broken down by JobSatisfaction (columns).

In [19]:
pivot_table = df.pivot_table(
    values='MonthlyIncome',
    index='Department',
    columns='JobSatisfaction',
    aggfunc='mean'
)
pivot_table

JobSatisfaction                    1            2            3            4
Department
Human Resources          8494.666667  8822.200000  8196.333333  7744.833333
Research & Development  10810.718750  8581.125000  8648.090909  8930.304348
Sales                    9795.789474  9590.461538  8459.461538  9045.000000

# 9. Create a new column
## Seniority  If YearsAtCompany > 10, value is'Senior' Otherwise, value is'Junior'

In [26]:
df['Seniority'] = np.where(df['YearsAtCompany'] > 10, 'Senior', 'Junior')
df['Seniority'].value_counts()

Seniority
Junior    104
Senior     96
Name: count, dtype: int64

In [24]:
df[['YearsAtCompany','Seniority']]

     YearsAtCompany Seniority
0                19    Senior
1                19    Senior
2                17    Senior
3                13    Senior
4                16    Senior
..              ...       ...
195               7    Junior
196              17    Senior
197               7    Junior
198              14    Senior
199              15    Senior

[200 rows x 2 columns]

# 10. Identify 'High Risk' employees who meet **ALL** these criteria:
**1.MaritalStatus is 'Single'**
**2. JobSatisfaction is less than**
**3.DistanceFromHome > 10**
**Display their EmployeeID and `JobRole**

In [28]:
high_risk = df[
    (df['MaritalStatus'] == 'Single') &
    (df['JobSatisfaction'] < 3) &
    (df['DistanceFromHome'] > 10) ]

high_risk[['EmployeeID', 'JobRole']]

     EmployeeID            JobRole
20         1021  Software Engineer
30         1031     Lab Technician
42         1043         HR Manager
43         1044         HR Manager
45         1046  Software Engineer
78         1079     Data Scientist
93         1094     Lab Technician
108        1109         Sales Exec
112        1113     Data Scientist
119        1120  Software Engineer
124        1125         HR Manager
159        1160         HR Manager
161        1162     Data Scientist
168        1169         HR Manager
169        1170         Sales Exec
172        1173  Software Engineer
174        1175         HR Manager
183        1184     Lab Technician
185        1186     Data Scientist